### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/saloonphp/laravel-plugin/pull/61/commits/bdf7ec8c1cbbbaace61bcc85dbf829640629cf0e?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-plugin.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "saloonphp/laravel-plugin": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by serwin35** [comment]
When will this PR be merged?

**Comment by Sammyjo20** [comment]
Hey @serwin35. Laravel 11 isn't out yet, so I will wait until it is released on March 11th.

**Comment by allanmcarvalho** [comment]
Hey @Sammyjo20, any idea from when this PR will merged? I need this plugin on my application.

**Comment by Sammyjo20** [comment]
Hey @allanmcarvalho I will be upgrading all my open source libraries today/tonight. Laravel 11 was only released 2 hours ago :D

**Comment by Sammyjo20** [comment]
I was waiting for orchestra/testbench v9 to be released which has now been released so I will update this tonight.

**Pull request merged**
