### PR TITLE
WIP: add response with request

### PR DESCRIPTION
**Pull request by Wulfheart**
Would close #3.
However, this is not as trivial as I previously thought. 
@Sammyjo20 do you know any way how I could get the full namespace and class name of the newly generated response?

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Maybe we assume the base namespace is in Http/Integrations? If an integration flag is specified, we can assume it is Http/Integrations/Integration1/Responses

**Comment by Sammyjo20** [comment]
Otherwise It could accept a full namespace?

Also just thought it could be cool if you could specify a connector as well as a response.

**Comment by Wulfheart** [comment]
Ok, so what is the way forward now?

**Comment by Sammyjo20** [comment]
Thank you for making this PR, but I think we should revisit this another time. It's definitely useful but I'd like to create a PR in the future that adds a couple of flags to the request:

--connector=NameOfConnector (assumes in the Http/Integrations folder)
--response=MyResponse (assumes in Http/Integrations/Responses folder)

**Pull request closed without merging**
