### PR TITLE
Namespace Fix

### LINKED ISSUE #4: Folder Structure
Currently the cli commands generate requests, responses and connectors in separate folders.
However, when writing multiple API integrations it becomes messy when these three from different applications become mixed up. Therefore I propose an refined command line experience consisting of the following:
1. I like the location in the Http folder as it deals with outgoing Http requests. I don't like the name Saloon for that folder. I suppose it is for branding purposes but I don't think that it is the right way forward because it doesn't clearly convey the purpose of the directory. I think it should be named something like `Integration`.
2. Furthermore I fear that different integrations become mixed up in a context with multiple integrations. Therefore I think it should contain multiple directories with the current structure in them (but the `Connectors` directory omitted as there is only one connector per API I suppose).
```
app/
├─ Http/
│  ├─ Integration/
│  │  ├─ Integration1/
│  │  │  ├─ Requests/
│  │  │  ├─ Responses/
│  │  │  ├─ Integration1Connector.php
│  │  ├─ Integration2/
│  │  │  ├─ Requests/
│  │  │  ├─ Responses/
│  │  │  ├─ Integration2Connector.php
```

3. Number 2 would also lead to an additional flag called something like `-i|--integration` to specify which integration is intended to have an addition.

What do you think about it?

I'd be willing to contribute this addition.

### PR DESCRIPTION
**Pull request by Wulfheart**
Closes #4.
Give it a try. Signature is `php artisan saloon:xyz <integration> <Class>`.

### CODE REVIEW

**Comment by Sammyjo20** [comment]
This looks good. I’ll give it a go tomorrow!

**Comment by Sammyjo20** [comment]
Would we be able to change it to `Integrations` because it matches better with "Controllers"  "Requests" etc

**Comment by Wulfheart** [comment]
@Sammyjo20 done!

**Comment by Sammyjo20** [comment]
I like the proposed solution, 100% happy for Connectors and Requests, however for responses and plugins I'm not sure.

What if I wanted to create a Saloon plugin that I can use across multiple integrations. The same with the responses, there might be my set of methods that I choose to use across different ones. Perhaps for the plugins/responses command, rather than it being a required parameter, it should be an option/argument instead to specify `--integration`. 

What do you think?

**Comment by Sammyjo20** [comment]
Also I'm wondering if it would be cool if Saloon's connector command's name could be optional? So if I wrote `php artisan saloon:connector Forge` it would automatically create Integrations/Forge/ForgeConnector?

**Review by Sammyjo20 — APPROVED** [review]
I'm going to merge this in now as the other comments aren't required. Great job! Thank you for this PR.

**Pull request merged**
